eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-239eb21d-054b-47a2-b01d-2486423bfef8.apps.cumuluslabs.io
    instance-info-replication-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 6

